### PR TITLE
When request method is POST, PUT, or PATCH.

### PR DESCRIPTION
**Pull request by yjinchun**
http://php.net/manual/en/reserved.variables.post.php
http://php.net/manual/en/wrappers.php.php

### CODE REVIEW

**Comment by dcramer** [comment]
Won't this exhaust the input stream so that no one else can read it?

**Comment by yjinchun** [comment]
Yes, you're right. It also needs to be changed.
I modified the reason here is that our team are using angular, transfer data to the back-end, not with a "form-data", nor is "form-urlencoded", but "request payload". This prevented us see the POST data in the Sentry.
So, if our set "Content-Type:application/x-www-form-urlencoded" able to solve this problem?
And, If it is a file? How to deal with more reasonable?
Thanks your answer.

**Comment by dcramer** [comment]
In certain situations I dont believe there will be a way to capture form data. I think ideally what we'd do here is having a special flag that says "form data not available" and show that in the UI, with a link to why. A basic requirement of Sentry is that it doesnt interfere with the app, and risking exhausting a stream to show debug information would be a problem. AFAIK there's no way around it.

**Comment by yjinchun** [comment]
I need to think more. 
Thanks.

**Pull request closed without merging**
